### ISSUE TITLE
Wired Issue

### ISSUE THREAD

**Issue by audvik** [ascsoftw/tall-crud-generator#1]
I am getting errors after installing this package. **I can't login.**
I've published config and views but also same issue arise.
Help needed for error provided below: Thank you in advance.
```
InvalidArgumentException
Unable to locate class or view [tall-crud-generator::label] for component [label].
```
using Breeze,Tailwind,Livewire,Alpine !

**Comment by ascsoftw** [comment]
Looks like a Cache Issue. Could you please configure your cache again

`php artisan config:cache`

**Comment by audvik** [comment]
No it's not cache issue. Tried other ways but finally got a tweak.
The error is that it's overriding laravel/breeze blade classes. 
My error in  login.blade.php is solved 
when I change all `x-class` to `x:tall-crud-generator::class` .
for example in login.blade.php, I have to change
```
<div>
        <x:tall-crud-generator::label for="email" :value="__('Email')" />
        <x:tall-crud-generator::input id="email" class="block w-full mt-1" type="email" name="email" :value="old('email')" required autofocus />
    </div>

    <div class="mt-4">
        <x:tall-crud-generator::label for="password" :value="__('Password')" />

        <x:tall-crud-generator::input id="password" class="block w-full mt-1"
                        type="password"
                        name="password"
                        required autocomplete="current-password" />
</div>
```
This tweak works but I have to change all breeze generated files.
Could you provide a solution to work breeze with your package.

**Comment by ascsoftw** [comment]
I can confirm the issue now. I am working on a fix.

**Comment by ascsoftw** [comment]
Could you please re-install the package using v1.0.1
This should fix the component name collision issue and you should be able to use it without changing any of the breeze files.

Let me know if you still have any issues.

**Comment by audvik** [comment]
Thank you so much. Issue solved.
