### ISSUE TITLE
How to Handle The `Select Fields` Step Issue

### ISSUE THREAD

**Issue by mahmoudmohamedramadan** [ascsoftw/tall-crud-generator#2]
I have installed this awesome package and I have run `composer require laravel/ui` command, then `php artisan ui bootstrap --auth` also

and I have followed the package steps, BUT in the `Select Fields` step as shown here
![{CF2FC43A-12A8-41D9-B339-DB13C9816755}](https://user-images.githubusercontent.com/48416569/125736817-25249e2f-219a-4b7f-94bb-932d3334a3cc.png)

 this issue triggered when I click **NEXT**
![{5FC1A363-7BF9-4323-A9A2-EB10581DA970}](https://user-images.githubusercontent.com/48416569/125736599-6282de28-700c-4f6c-b0ab-eedc9ab08db4.png)

**How I can solve this issue?**

**Comment by ascsoftw** [comment]
The error is coming when trying to determine the Relation of a given Model. Will fix this soon.

**Comment by ascsoftw** [comment]
This should be fixed in the latest release (1.2.2). Let me know in case of any issues.

**Comment by mahmoudmohamedramadan** [comment]
awesome, I'll check it out
