### ISSUE TITLE
Design issue in the config page after installation

### ISSUE THREAD

**Issue by ramyaaravind5252** [ascsoftw/tall-crud-generator#25]
We followed the steps as suggested in the documentation. Livewire, Tailwind css , Alpinejs are installed. Installed  the crud generator.
Used @livewire('tall-crud-generator') in one of my blade file. But the design is completly broken and unable to proceed. Can you please check and respond as early as possible.

Using Laravel 10, Php 8.1

![image](https://github.com/ascsoftw/tall-crud-generator/assets/144761652/a9d2562c-e7e7-4adf-b556-e62ce1fd9693)

**Comment by ascsoftw** [comment]
Hi,

Please check and confirm if there is a Server Error or is it a frontend issue.

Also please confirm that you are not using Livewire 3 which is not yet supported.

**Comment by ramyaaravind5252** [comment]
Hi, That design issue fixed on  installing Laravel/breeze. But attributes part and final button(generate files) were not working. I was using Livewire3. Now I downgraded to 2.x-dev. Is this okay. Now I am not able to proceed to step 2. Getting the below error. 
Undefined variable $__livewire

![image](https://github.com/ascsoftw/tall-crud-generator/assets/144761652/57cd7b30-90e6-4047-9afa-490146091fee)


Is there some thing I am missing

**Comment by ramyaaravind5252** [comment]
Hi,  Thanks for the response. I have downgraded the Livewire, still having
some issues, updated in ticket. Please check and let me know.

**Comment by ascsoftw** [comment]
Hi,
The error message suggests that Livewire is not configured properly. Please make sure that TALL Stack is properly configured before using the Plugin.

**Comment by ramyaaravind5252** [comment]
Reinstalling the laravel,breeze,livewire and tall package fixed the issue. Thanks for the response.
