### ISSUE TITLE
Undefined index: belongsToMany (View: /Users/project/vendor/ascsoftw/tall-crud-generator/resources/views/livewire/step4.blade.php)

### ISSUE THREAD

**Issue by vivekaris** [ascsoftw/tall-crud-generator#6]
Undefined index: belongsToMany (View: /Users/project/vendor/ascsoftw/tall-crud-generator/resources/views/livewire/step4.blade.php)

<x:tall-crud-generator::dialog-modal wire:model="confirmingBelongsToMany">

    <x-slot name="title">

        Add a Belongs to Many Relationship

    </x-slot>

    <x-slot name="content">

        <div class="mt-4">

            <div>

                <x:tall-crud-generator::label>Select Relationship</x:tall-crud-generator::label>

                <x:tall-crud-generator::select class="block mt-1 w-1/2" wire:model.lazy="belongsToManyRelation.name">

                    <option value="">-Please Select-</option>

                    @foreach($allRelations['belongsToMany'] as $c)

                    <option value="{{$c['name']}}">{{$c['name']}}</option>

                    @endforeach

                </x:tall-crud-generator::select>

                @error('belongsToManyRelation.name') <x:tall-crud-generator::error-message>{{$message}}</x:tall-crud-generator::error-message> @enderror

            </div>

**Comment by ascsoftw** [comment]
Hi Vivek,

Thanks for bringing it up. This has been fixed in the latest Release v.1.3.0
