### ISSUE TITLE
Livewire\Exceptions\ComponentNotFoundException Unable to find component: [ComponentName-child]

### ISSUE THREAD

**Issue by locopine** [ascsoftw/tall-crud-generator#9]
My congratulations on the excellent application! Great job!

I leave here my report regarding the "difficulties" I faced with the last release:

After generating a CRUD with the application I encountered the following situation:

- In the main view with the generated directive as below:
`@livewire('LaravelTips')`

- And in the child view with the generated directive as below:
`@livewire('LaravelTips-child')    @livewire('livewire-toast')`

- However, when accessing the CRUD, an exception was thrown:
> **Livewire\Exceptions\ComponentNotFoundException**
> **Unable to find component: [LaravelTips]** and;
> **Livewire\Exceptions\ComponentNotFoundException**
> **Unable to find component: [LaravelTips-child]** respectively.

- In my case, it worked by being corrected to:
`@livewire('LaravelTips')` and child to
`@livewire('laravel-tips-child')    @livewire('livewire-toast')`

Another thing I noticed was that, apparently, the LIVEWIRE components, are being generated during the CRUD steps and, at the end when being named the component does not finish the CRUD generation under the claim that the name is already in use!

Thx.

**Comment by ascsoftw** [comment]
@locopine 

Thank you so much for finding the bug and creating the issue. I will work on the fixes.

**Comment by ascsoftw** [comment]
@locopine 

Generated Code for Component with CamelCased Name like LaravelTips has been fixed in the latest release.
